### ISSUE TITLE
Use new library for building plots

### ISSUE THREAD

**Issue by savelevvo** [Seleznev-nvkz/AirBot#9]
Current lib doesn't work with docker.

**Comment by savelevvo** [comment]
- https://github.com/wcharczuk/go-chart -- try this one first
- https://github.com/gonum/plot
- https://github.com/vdobler/chart
- https://github.com/Arafatk/glot -- current lib; doesn't work

**Comment by Seleznev-nvkz** [comment]
glot working with docker, but with bugs. go-chart is native, use this

**Comment by savelevvo** [comment]
Added `go-chart` in [967b4ef](https://github.com/Seleznev-nvkz/AirBot/commit/967b4ef88ad337a3021584d723656884a3c4586e).
